baseURL: "https://eddygarrat.github.io/Ji/"
languageCode: "en-us"
title: "JiShu"
theme: "hugo-PaperMod"

paginate: 5

params:
  ShowBreadCrumbs: false
  assets:
    favicon: "images/favicon.png"

  profileMode:
    enabled: true
    title: "Jishnu"
    subtitle: "Welcome to my site!"
    extrainfo: "I am Jishnu, and I try to explore"

  socialIcons:
    - name: github
      url: "https://github.com/eddygarrat"
    - name: twitter
      url: "https://twitter.com/yourusername"
name: GitHub Pages

profileMode:
    enabled: true # needs to be explicitly set
    title: Jishu
    subtitle: "Hello there!"
    extrainfo: "I am Jishnu,No designation yet ,
In my free time, I like to listen to music, and write"
    extraextrainfo: "I'm up f"
    imageUrl: me.jpeg
    imageWidth: 200
    imageHeight: 200
    imageTitle: its a me !


menu:
  main:
    - identifier: home
      name: Home
      url: ""
      weight: 1
    - identifier: academics
      name: Academics
      url: /academics/
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    #- identifier: archives
    #  name: Archives
    #  url: /archives/
    #  weight: 15
    - identifier: mylogs
      name: My Logs
      url: /mylogs/
      weight: 15
   
    #- identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 25

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (submodules)
        fetch-depth: 0    # Fetch all history for .GitInfo and proper deploy

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.1'

    - name: Build
      run: hugo --gc --minify --baseURL "https://eddygarrat.github.io/JimShu/"

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

