baseURL: "https://eddygarrat.github.io/Ji/"
languageCode: "en-us"
title: "JiShu"
theme: hugo-PaperMod

paginate: 5

params:
  ShowBreadCrumbs: false
  
  profileMode:
    enabled: true
    title: "Jishnu"
    subtitle: "Welcome to my site!"
    extrainfo: "I am Jishnu, Blah Blah"
    
    imageUrl: me.jpeg
    imageWidth: 200
    imageHeight: 200

  socialIcons:
    - name: github
      url: "https://github.com/eddygarrat"
    - name: twitter
      url: "https://twitter.com/yourusername"
name: GitHub Pages




menu:
  main:
    - identifier: home
      name: Home
      url: ""
      weight: 1
    - identifier: academics
      name: Academics
      url: /academics/
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    #- identifier: archives
    #  name: Archives
    #  url: /archives/
    #  weight: 15
    - identifier: mylogs
      name: My Logs
      url: /mylogs/
      weight: 15
    - identifier: Life
      name: Life
      url: /life/
      weight: 25


 

